#set_property PACKAGE_PIN B6 [get_ports clk_100MHz]

set_property PACKAGE_PIN V14 [get_ports {leds[2]}]
set_property PACKAGE_PIN V13 [get_ports {leds[1]}]
set_property PACKAGE_PIN V12 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PULLUP true [get_ports {leds[2]}]
set_property PULLUP true [get_ports {leds[1]}]
set_property PULLUP true [get_ports {leds[0]}]
set_property DRIVE 8 [get_ports {leds[2]}]
set_property DRIVE 8 [get_ports {leds[1]}]
set_property DRIVE 8 [get_ports {leds[0]}]